INSERT INTO INVENTORY VALUES(1,'oak table',11.0,11);
INSERT INTO INVENTORY VALUES(2,'pine chair',22,22);
INSERT INTO INVENTORY VALUES(3,'Turquoise',33,33);
INSERT INTO STAFF VALUES(1,'yu','xi');
INSERT INTO STAFF VALUES(2,'ruby','zhang');


