DROP TABLE INVENTORY CASCADE;
CREATE TABLE INVENTORY (
  ProductID   INTEGER not null, 
  ProductDesc    VARCHAR(30) not null,
  ProductPrice     NUMERIC(8,2) not null,
  ProductStockAmount    INTEGER not null,
  PRIMARY KEY (ProductID),
  CHECK(ProductPrice>0),
  CHECK(ProductStockAmount)
--  foreign key (dno) references department(dnumber)
);
-- CREATE SEQUENCE sequence_1 
--     START WITH 0  
--     INCREMENT BY 1 ;  
DROP TABLE ORDERS CASCADE;
CREATE TABLE ORDERS (
OrderID     INTEGER not null,
OrderType    VARCHAR(30) not null,
OrderCompleted    INTEGER not null,
OrderPlaced    DATE not null,
PRIMARY KEY (OrderID),
CHECK(OrderType='InStore'OR OrderType='Collection'OR OrderType='Delivery' ),
CHECK(OrderCompleted=1 OR OrderCompleted=0)
);
DROP TABLE ORDER_PRODUCTS CASCADE;
CREATE TABLE ORDER_PRODUCTS(
OrderID     INTEGER ,
ProductID    INTEGER ,
ProductQuantity    INTEGER not null,
 CHECK(ProductQuantity>0),
UNIQUE(OrderID,ProductID),
FOREIGN KEY(OrderID) REFERENCES ORDERS(OrderID) ON DELETE SET NULL ON UPDATE CASCADE,
FOREIGN KEY(ProductID) REFERENCES INVENTORY(ProductID)  ON DELETE SET NULL ON UPDATE CASCADE
);
DROP TABLE DELIVERIES CASCADE;
CREATE TABLE DELIVERIES(
OrderID     INTEGER ,
FName    VARCHAR(30) not null,
LName    VARCHAR(30) not null,
House    VARCHAR(30) not null,
Street    VARCHAR(30) not null,
City    VARCHAR(30) not null,
DeliveryDate   DATE not null,
FOREIGN KEY(OrderID) REFERENCES ORDERS(OrderID)  ON DELETE SET NULL ON UPDATE CASCADE
);
DROP TABLE COLLECTIONS CASCADE ;
CREATE TABLE COLLECTIONS(
OrderID    INTEGER ,
FName    VARCHAR(30) not null,
LName    VARCHAR(30) not null,
CollectionDate   DATE not null,
FOREIGN KEY(OrderID) REFERENCES ORDERS(OrderID)  ON DELETE SET NULL ON UPDATE CASCADE
);
DROP TABLE STAFF CASCADE;
CREATE TABLE STAFF(
StaffID    INTEGER not null,
FName    VARCHAR(30) not null,
LName    VARCHAR(30) not null,
PRIMARY KEY(StaffID)
);
DROP TABLE STAFF_ORDERS CASCADE;
CREATE TABLE STAFF_ORDERS(
StaffID    INTEGER ,
OrderID    INTEGER ,
FOREIGN KEY(StaffID) REFERENCES STAFF(StaffID)  ON DELETE SET NULL ON UPDATE CASCADE,
FOREIGN KEY(OrderID) REFERENCES ORDERS(OrderID)  ON DELETE SET NULL ON UPDATE CASCADE
);
